# The URL the site will be built for
base_url = "https://sveatlo.io"

# set theme
theme = "sam"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# paginate stuff
paginate_by = 5

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

sam_menu = [
    { text = "about me", link = "/about" },
    { text = "blog", link = "/blog" },
    { text = "github", link = "https://github.com/sveatlo", target = "_blank" },
    { text = "linkedin", link = "https://www.linkedin.com/in/sveatlo", target = "_blank" }
]

[extra.sam_footer]
text = "contact me at <a href=\"mailto:hello@sveatlo.me\">hello@sveatlo.me</a>"
